language: node_js
node_js:
  - "6.0.0"

branches:
  only:
    - master
    - /^\d\.\d+$/

install:
  - npm install
  - npm install -g gulp

before_script:

script:
  - gulp build:prod
  - gulp copy
  - gulp copy:assets
  - gulp styles
  - gulp manifest

after_script:
  - git config --global user.name "TRAVIS-CI"
  - git config --global user.email "jan@janbaer.de"
  - ./deploy_travis.sh $TRAVIS_TAG $GH_TOKEN

env:
  global:
  - secure: "LbvGLIwah72Sv1ynDBMrBq+AUQSvCE/9ijDq0hywD7ymPRqaTmik8gR5aQnN+p1ocaDKLjDm4ay8x2LW+Ws6dXzAVepIvcuRstDfdVvSK0eMiaeTHbnuiqcjFunEX1MXqtPobxKxuf34m3yTbKK3KDSxWCd3LPw2MDKx5deFoo9EeQIt+cQzChxssFpzE67NYnNBxpE/6cJizKX8bx7cnsek6tDOvEuf4ljpVGnf/bKJsQe0kL5SWatmkE18eLGFfA6rEZEMPMMG8ams1MT2YbgEhq2+UBRbKU8EHPBgo4J7/7765Wkg4ZeUJOkdCARs8PqWqPKK4mY1v22EzanLi+TyUDwcWUctK6WqQzxAySZ5U8PqQQkzX5aroia5IDfAMm+RWF6pgFjDaxYS2P5ld6cCukfdWJ/vuApeBnI7UmEGBhG7y13YAfXo5ENzdxp4bTBWn5suekiWSjPnbUWPdTN6rVhg/i3Iu/WZmcf9Wp8/BDuSe/x2wSybFhRmBTkQxq+JDnpa631Px3HD1r5w4T7wBKkzaSZO2S7wt8HwLYMutSw6OUS8u0uuvW6BXyIioQfS0tC1eTv42KeOZZ9ZBkQq709sCRWOqtrxeMLaRSruYtvCZ5IvAeRc4+whnU/U432uEHxpfPYVQpdlT5/+L7IUMu5pL3F2rfmMvNGV99c="

