language: node_js
node_js:
  - "4.2.4"

install:
  - npm install
  - npm install -g gulp

script:
  - gulp buildAndDeploy --tag=${TRAVIS_TAG}

env:
  global:
  - secure: vb4rdtR56qfCGjb2BpZKQO5mF1XgE1k2IkW/MOVaccvcUrEjY+X4oHd9ltCLj7PwxyrahzjPRKaVOnQlDrCj7ztN8wo4ErKs9A5hYMSRafRXZQVL69/MAH6wu4b9QFAjioukEsbVDfL3i78gKyUcq0hTT7h+oJ8pgDQXX/R8qfKCn94q8UzIOci706stowCVpMf+hvNmKB8s51Y4SS+co4gcrGsvsdfAGrLMPImlx196C4OwVxnkBk4z3APjDn5QR148YzBXcOtqosJR8cbrfHbyAlh+jJWMenH/b7LhBuTgQD/eNe4c3sCVABDRNYjcIA8CYX8xI2nZo00akR8rTYS30laVctuTvDG1uDy8d5tynYxVy+jhImnPdAtNz3F7iqirV4mQSmEdK/k/KWgLUnN7Gf/Yw79AiR6ijQdgvyQrwmlz3Kuu2okMzABX68VRzaCIEmonq6Vbf79EjTcwdPMa0gQ+IvAR7Vx7OG7uvUCtmBtJEnKo5MXwER+o03x0nOcNj1l/ImoX6Uw32RVx7aULsuTkoVlJZPQvGxD59uojw5hz0z199o81Caa1xZoKPHbPAwgzjafW2TqZoMwXfxgmPKjAX6gpEBQd30v/7G6hcNzkg6fSLPR4Pan6zQDXxfTF1k5ryWS2wnkhJS2IEJ0T9xsu7wwvhdomyU6kXn0=
