language: node_js
node_js:
  - "6.10.1"

branches:
  only:
    - master
    - /^\d\.\d+$/

install:
  - npm install -g yarn gulp
  - npm install

before_script:

script:
  - gulp build:prod
  - gulp copy
  - gulp copy:assets
  - gulp styles
  - gulp manifest

after_script:
  - git config --global user.name "TRAVIS-CI"
  - git config --global user.email "jan@janbaer.de"
  - ./deploy_travis.sh $GH_TOKEN $TRAVIS_TAG

