language: node_js
node_js:
  - "4.2.4"

branches:
  only:
    - master

install:
  - npm install
  - npm install -g gulp

before_script:
  - test $TRAVIS_TAG != ''

script:
  - gulp build:prod
  - gulp copy
  - gulp copy:assets
  - gulp styles

after_script:
  - git config --global user.name "TRAVIS-CI"
  - git config --global user.email "jan@janbaer.de"
  - git clone https://janbaer:${GH_TOKEN}@github.com/howcani-project/howcani-project.github.io.git dist
  - cd dist
  - git rm -r .
  - cp -r ../build/* ./
  - rm ./scripts/*.js.map
  - rm ./styles/*.css.map
  - git add -u && git add .
  - git commit -m "Version ${TRAVIS_TAG}"
  - git push origin master

env:
  global:
  - secure: "y+tWVx0RWYrvnQBX9v2nJfYEBD5h/7CH/kxu6G6CKCDfwfeNF1a08GHrB8Q2OK3hdpAOw51EnUpmnk9+TB2g7b+mDsnfhtd6pfXxmFMeFgyeAcYbjzqsnd4VKaiPTOf+g/XGzC+pYPCCBFlnT1r9orSjgxvKtk2hdB4xGkB1bEm+4409X+QT/dCnIvfn1/PPkgtq+cA3GfwHF/ZGPzYBbKL+xJlTPIda9Jg3BstbsBJ0lov7gwoRwqaueFsAs5XkxDkgUjxk0uv0Ctzg8YSTneDkrXI62qdebiIWj9ctiKpzTYlzyuPE6KjYQLPloHLDLiOZO6IX8bXShdd7RdBqmngZ8SwnQpe2S3XswxqGaJHWHvPC0tr5GA0+A1qoytHXVbpW3l1E/fjqUWIyW+tvtU3op02VK1EqT9bya4KuujoHPTrHt5wBBNDS7r4jGes4PAp1Ajg+Q4cIYxt1b+FKB3mFmq66ZP1o+kOFywHGIXjJTVoWmq/6ZDdwhDmFqt5qwNJhUEGFzY5/Jgde2/jRGBogPcKf2+lNvtSTtL4KND1Nknoxvv0cFQJQ5syew8jYAHp3gxAoqvsMTBH1P9qy9yFepmFloobovxdeHnHPpWfSpGA10qi2K6QWed5d26unDFUmjRyeDyibJjbWhZtEyLOb2OsL/x7OUIJTKDe/HwU="
