language: node_js
node_js:
  - "4.2.4"

install:
  - npm install
  - npm install -g gulp

script:
  - gulp buildAndDeploy --tag=${TRAVIS_TAG}

env:
  global:
    secure: dmc10Km5lkm6rldVj0hFQiO9ZxA0ekgl9MeZ+q05EnqVRqygzSMDQWBBnTsH3xTEmVQIYLeTCvfUC57bfNKqCxBZ0Ot8YwL2krQ42D0bI4sCH+fL5QrvhG/ViPSe9OBE3LCL/fhkmec4x7f7ylDAwopC7S6wdXW9Il97YYBUCxRsDfZW+z8DVZYp4yRUKHrfxtQ6WsNadm8cbsu4P80slEl4sG/Feh4x6uGR6Ek4nPCagAQsYJpEwJcOQgRH3RgNqPBQZ6QrB7y1KJQ7U8dIy/M0JTRYzzevwMq7jz8EZ/dloseg+ghTRYXFznzK4CL0PIKLiarwQG2YW4/vjHFKpxyE7y58HfYCe0/ErJTaMXD3mCLWTeZPsYbKpLessU1pFOBrqHF3BohMzMoAQWFIrZWY8wo+97oO41peNbuJJ8qQnYtQCx8KHW4R6vipTax+e2wQA9lzD8jtQuKeg+m1Xo3H53rv25v1dhPoJohoMHIzjYNbCdwRnt3Y/Ar3ngjsw9L/0l+hV6Bi7fLNo6DZlwssQs3iso9u2jBry2633RF0FtRIkiWa2dRTyJA4Xfxh+eM32ZwO9n2AJNVh+BmA2YlLG/EmlpMdV6Ku1v9LgrusyGjbrXW9eLgq8AFMjSHxODe1OhclSpgDu72Wc81BBGfR5lII59gXrdTZA2Y6vDk=

